@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_TOP_DOWN()

Person(user, "Пользователь", "Управляет системой через веб интерфейс")
System(system, "Монолитное приложение умного дома", "Позволяет управлять отоплением")
System_Ext(sensorDevice, "Температурный сенсор", "Передаёт данные о температуре")

Rel(user, system, "Управляет системой и настраивает параметры", "HTTPS")
Rel(sensorDevice, system, "Отправляет данные температуры", "JDBC/PostgreSQL")

@enduml
